services:
  php:
    container_name: php-container
    build:
        context: .docker/php
    ports:
        - "9000:9000"
    volumes:
        - .:/var/www/project
    depends_on:
        - postgres
      
  nginx:
      container_name: nginx-container
      build:
        context: ./docker/nginx
      ports:
          - ${NGINX_PORT}:80
      volumes:
          - .:/var/www/project:ro
          - ./docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      restart: always
      depends_on:
          - php
  postgres:
    container_name: postgres-container
    build:
      context: ./docker/postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###

networks:
  nginx-php-database: